- src/site/apt/index.apt.vm
- [X ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCHECKSTYLE) filed 
- [X ] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Format the pull request title like `[MCHECKSTYLE-XXX] - Fixes bug in ApproximateQuantiles`,
where you replace `MCHECKSTYLE-XXX` with the appropriate JIRA issue.
> [MCHECKSTYLE-364]  -Fix links

- src/site/apt/index.apt.vm
fixes MCHECKSTYLE-364
- [X ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCHECKSTYLE) filed 
- [ X] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Format the pull request title like `[MCHECKSTYLE-XXX] - Fixes bug in ApproximateQuantiles`,
- [X ] Write a …
> [MCHECKSTYLE-364] - The wiki on codehaus is no more

- README.md
@khmarbaise
- [X ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MCHECKSTYLE) filed 
- [ X] Each commit in the pull request should have a meaningful subject line and body.
- [X ] Format the pull request title like `[MCHECKSTYLE-XXX] - Fixes bug in ApproximateQuantiles`,
- [ X] Write a pull request …
> [MCHECKSTYLE-358] fix mailing list address

- pom.xml
> update maven site plugin

- src/main/java/org/apache/maven/plugins/checkstyle/CheckstyleReport.java
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
---
:heavy_check_mark: [Travis build with undelivered commit status](https://travis-ci.org/github/apache/maven-checkstyle-plugin/builds/671245555)
> (doc) Remove method to simply inherit it

- src/main/java/org/apache/maven/plugins/checkstyle/AbstractCheckstyleReport.java
- src/main/java/org/apache/maven/plugins/checkstyle/CheckstyleViolationCheckMojo.java
- src/main/java/org/apache/maven/plugins/checkstyle/resource/LicenseResourceManager.java
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.
---
:heavy_check_mark: [Travis build with undelivered commit status](https://travis-ci.org/github/apache/maven-checkstyle-plugin/builds/671245778)
> (doc) Remove unnecessary casts

- src/main/java/org/apache/maven/plugins/checkstyle/ReportResource.java
---
:heavy_check_mark: [Travis build](https://travis-ci.org/github/apache/maven-checkstyle-plugin/builds/671329143)
> (doc) Remove expression that always evaluates to true

- src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java
> use try with resources instead of deprecated method

- src/main/java/org/apache/maven/plugins/checkstyle/rss/VelocityTemplate.java
> use try with resources and charset

- src/main/java/org/apache/maven/plugins/checkstyle/Violation.java
- src/test/java/org/apache/maven/plugins/checkstyle/ViolationTest.java
Fixes [MCHECKSTYLE-401](https://issues.apache.org/jira/browse/MCHECKSTYLE-401). 
Both `file` and `line` field are nullable in the constructor. Equals method now uses `Objects.equals()` for those fields to handle the nullability. Also added a test for the `equals()` method.
If …
> [MCHECKSTYLE-401] - NullPointerException in Violation class

- src/site/apt/examples/upgrading-checkstyle.apt.vm
`<build>`'s closing tag was missing a `/`.
To make clear that …
> (docs) Fix </build> tag in config snippet

- src/site/apt/examples/custom-property-expansion.apt.vm
Jira: [MCHECKSTYLE-414](https://issues.apache.org/jira/browse/MCHECKSTYLE-414)
I did include an extra example of how to use multiple properties in maven without the use of the properties file. Lmk if I should split this out into a separate PR
If your pull request is about ~20 …
> [MCHECKSTYLE-414] - documentation: property expansion example does not parse

- src/it/MCHECKSTYLE-357-with-header-override/pom.xml
- src/it/MCHECKSTYLE-357/pom.xml
- src/it/checkstyle-goal/pom.xml
- src/it/checkstyle-report/pom.xml
- src/main/java/org/apache/maven/plugins/checkstyle/AbstractCheckstyleReport.java
- src/main/java/org/apache/maven/plugins/checkstyle/CheckstyleReportGenerator.java
- src/main/java/org/apache/maven/plugins/checkstyle/rss/CheckstyleRssGenerator.java
- src/main/java/org/apache/maven/plugins/checkstyle/rss/CheckstyleRssGeneratorRequest.java
- src/main/java/org/apache/maven/plugins/checkstyle/rss/DefaultCheckstyleRssGenerator.java
- src/main/java/org/apache/maven/plugins/checkstyle/rss/VelocityTemplate.java
> [MCHECKSTYLE-418] Deprecate RSS feature and disable by default

- pom.xml
- src/it/MCHECKSTYLE-214-basedir-resource/verify.groovy
- src/it/checkstyle-goal/verify.groovy
- src/it/checkstyle-report/verify.groovy
Adds support to run integration tests with Java 19+
> [MCHECKSTYLE-427] Upgrade maven-invoker-plugin to 3.5.0

- src/main/java/org/apache/maven/plugins/checkstyle/AbstractCheckstyleReport.java
- src/main/java/org/apache/maven/plugins/checkstyle/CheckstyleViolationCheckMojo.java
- src/main/java/org/apache/maven/plugins/checkstyle/exec/DefaultCheckstyleExecutor.java
Continuation of https://issues.apache.org/jira/browse/MNG-6829
Review requested of @elharo
Use this link to re-run the recipe: https://public.moderne.io/recipes/org.openrewrite.java.migrate.apache.commons.lang.IsNotEmptyToJdk?organizationId=QXBhY2hlIE1hdmVu
If your pull …
> [MNG-6829] Replace StringUtils#isEmpty(String) and #isNotEmpty(String)

- src/site/apt/examples/custom-developed-checkstyle.apt.vm
> (doc) fix typo in "ckecks"

- src/main/java/org/apache/maven/plugins/checkstyle/CheckstyleReportRenderer.java
Fix rule link format(https://checkstyle.org/checks/{category}/{ruleName}.html) since older links (https://checkstyle.org/config_{category}.html#{ruleName}) cause a 404 error.
[Individual Contributor …
> [MCHECKSTYLE-450] Checkstyle rule link format results in 404

- pom.xml
> Add missing dependencies

- pom.xml
This closes #137
To make clear that you license your …
> [MCHECKSTYLE-448] Upgrade to Parent 42 and Maven 3.6.3

- src/it/MCHECKSTYLE-219-no-license_failure/invoker.properties
- src/it/MCHECKSTYLE-219-no-license_success/invoker.properties
- src/it/MCHECKSTYLE-225-LICENSE.txt/invoker.properties
- src/it/MCHECKSTYLE-225-customHeader/invoker.properties
- src/it/MCHECKSTYLE-225-pluginManagement/invoker.properties
- src/it/MCHECKSTYLE-253-jdk8/invoker.properties
- src/it/MCHECKSTYLE-295/invoker.properties
- src/it/MCHECKSTYLE-357-with-header-override/invoker.properties
- src/it/MCHECKSTYLE-357/invoker.properties
- src/it/MCHECKSTYLE-365/invoker.properties
- src/it/MCHECKSTYLE-371/invoker.properties
- src/it/inlinerules/invoker.properties
> Remove outdated invoker conditions

- src/site/xdoc/download.xml.vm
> [MCHECKSTYLE-441] Refresh download page

- .asf.yaml
> protect 3.4.x branch
